'''
    ======================================================
    Cubo semantico para validar los tipos de los operandos
    que se utilizan en las operaciones
    La primer llave corresponde al operando izquierdo
    La segunda llave corresponde al operando derecho
    La tercer llave corresponde a la operacion
    La cuarta llave corresponde al tipo del resultado
    ====================================================
'''

cuboSemantico = {
    "int": {
        "int": {
            "+":"int", 
            "-":"int", 
            "*":"int", 
            "/":"int", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"int",
            "==": "bool", 
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"float", 
            "-":"float", 
            "*":"float", 
            "/":"float", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"int", 
            "==": "bool",
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        },  
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==": "Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==": "Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
    }, 
    "float":{
        "int": {
            "+":"float", 
            "-":"float", 
            "*":"float", 
            "/":"float", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"float",
            "==": "bool", 
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"float", 
            "-":"float", 
            "*":"float", 
            "/":"float", 
            ">":"bool", 
            ">=":"bool",
            "<=":"bool",
            "<":"bool", 
            "=":"float", 
            "==": "bool",
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        },  
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error",
            "==":"Error", 
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error",
            "==":"Error", 
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
    }, 
    "bool":{
        "int": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"bool", 
            "==":"bool",
            "<>":"bool",
            "and":"bool", 
            "or":"bool",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
    },
    "string":{
        "int": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        }, 
        "float": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },  
        "bool": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"Error", 
            "==":"Error",
            "<>":"Error",
            "and":"Error", 
            "or":"Error",
        },
        "string": {
            "+":"Error", 
            "-":"Error", 
            "*":"Error", 
            "/":"Error", 
            ">":"Error", 
            ">=":"Error",
            "<=":"Error",
            "<":"Error", 
            "=":"string", 
            "==":"bool",
            "<>":"bool",
            "and":"Error", 
            "or":"Error",
        }, 
    }, 
}
